button:
  - platform: test_integration

rest_command:
  ping_google:
    url: "https://www.google.com"
    method: GET

script:
  notify_button_pressed:
    sequence:
      - service: persistent_notification.create
        data:
          title: "Button Test"
          message: "Dein Test-Button wurde erfolgreich gedrückt!"